### ISSUE TITLE
0.1 todo list

### ISSUE THREAD

**Issue by newbe36524** [RushGet/RushGet#3]
- [x] github action to publish release
- [x] README.md
- [ ] License
- [x] github action to build when pull request
- [ ] Renovate config to bulk update crate
- [ ] static web site to host latest release
